### ISSUE TITLE
参考官网在cmake编译时出错了

### ISSUE THREAD

**Issue by MellonGuan** [seetaresearch/dragon#1]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"
Python 3.6.8 (default, May  7 2019, 14:58:50) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.

![screencapture-dragon-seetatech-helper-install-html-2019-08-07-17_15_09](https://user-images.githubusercontent.com/19337606/62610948-41376500-b937-11e9-979b-71d325155a62.png)

root@d32d19b49eca:/opt/Dragon7801/Dragon/Dragon/build# cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python (found version "3.5.2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- Found NumPy: /usr/local/lib/python3.5/dist-packages/numpy/core/include (found version "1.15.4") 
-- NumPy ver. 1.15.4 found (include: /usr/local/lib/python3.5/dist-packages/numpy/core/include)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "9.0") 
-- C++11 support has been enabled by default.
-- Use Python3 [Optional]
-- Use CUDA [Optional]
-- Use CUDNN [Optional]
-- Use OpenMP [Optional]
-- Generate Proto Files (ref: /opt/Dragon7801/Dragon/Dragon/src/proto/dragon.proto)
-- Generate Proto Files (ref: /opt/Dragon7801/Dragon/Dragon/src/proto/caffemodel.proto)
-- Generate Proto Files (ref: /opt/Dragon7801/Dragon/Dragon/src/proto/onnx.proto)
-- Found Python Module: /opt/Dragon7801/Dragon/Dragon/modules/python
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_LIBRARY (ADVANCED)
    linked by target "dragon_python" in directory /opt/Dragon7801/Dragon/Dragon/modules/python
CUDA_curand_LIBRARY (ADVANCED)
    linked by target "dragon_python" in directory /opt/Dragon7801/Dragon/Dragon/modules/python

-- Configuring incomplete, errors occurred!
See also "/opt/Dragon7801/Dragon/Dragon/build/CMakeFiles/CMakeOutput.log".
See also "/opt/Dragon7801/Dragon/Dragon/build/CMakeFiles/CMakeError.log".

**Comment by PhyscalX** [comment]
Your cuda environment is not configured correctly. Check again.

Close this issue.
