### ISSUE TITLE
参考官网dockerfile报Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-02yn83yi/matplotlib/ You are using pip version 8.1.1, however version 19.2.1 is available. You should consider upgrading via the 'pip install --upgrade pip' command.

### ISSUE THREAD

**Issue by MellonGuan** [seetaresearch/dragon#2]
希望参考文档里能多一些常见的安装问题怎么解决
系统
cuda: 
NVIDIA-SMI 430.26       Driver Version: 430.26       CUDA Version: 10.2   

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

python 
Python 3.6.8 (default, May  7 2019, 14:58:50) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.

执行步骤和报错信息：
root@hp-desktop:/data/Dragon/Docker/ubuntu-16.04-cuda9.0-cudnn7# ls
Dockerfile
root@hp-desktop:/data/Dragon/Docker/ubuntu-16.04-cuda9.0-cudnn7# python
Python 3.6.8 (default, May  7 2019, 14:58:50) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()
root@hp-desktop:/data/Dragon/Docker/ubuntu-16.04-cuda9.0-cudnn7# docker build .
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04
 ---> a686b859d874
Step 2/7 : RUN rm /etc/apt/sources.list.d/cuda.list && rm /etc/apt/sources.list.d/nvidia-ml.list &&     apt-get update && apt-get install -y --no-install-recommends     build-essential     cmake     git     wget     unzip     ssh     vim     libtbb-dev     libsdl2-dev     libnuma-dev     libprotobuf-dev     protobuf-compiler     libopencv-dev     libboost-all-dev     libnccl2     libnccl-dev     python3-pip     python3-dev     python3-pyqt4     python3-tk     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 059200d7f7b5
Step 3/7 : RUN pip3 install --no-cache-dir --upgrade setuptools wheel -i https://pypi.tuna.tsinghua.edu.cn/simple &&     pip3 install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple     numpy     protobuf     lmdb     opencv-python     six     Pillow     matplotlib     scikit-image     pyyaml     cython
 ---> Running in dcf55cf8c907
Collecting setuptools
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/ec/51/f45cea425fd5cb0b0380f5b0f048ebc1da5b417e48d304838c02d6288a1e/setuptools-41.0.1-py2.py3-none-any.whl (575kB)
Collecting wheel
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
Installing collected packages: setuptools, wheel
Successfully installed setuptools-41.0.1 wheel-0.33.4
You are using pip version 8.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting numpy
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/69/25/eef8d362bd216b11e7d005331a3cca3d19b0aa57569bde680070109b745c/numpy-1.17.0-cp35-cp35m-manylinux1_x86_64.whl (20.2MB)
Collecting protobuf
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/55/34/7158a5ec978f12307eb361a8c4fdd867a8e2a0ab63fac99e5f555ee796d2/protobuf-3.9.0-cp35-cp35m-manylinux1_x86_64.whl (1.2MB)
Collecting lmdb
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/86/5c/6ad690daeaa00b328606bf2fa435244a11cc2dd9aedac6ef4d2ef2a21f6e/lmdb-0.96.tar.gz (869kB)
Collecting opencv-python
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/fe/c8/421eeac942ebc89552a5c90c2141b936be9cfde24dc3c6eeb472c62d1f8e/opencv_python-4.1.0.25-cp35-cp35m-manylinux1_x86_64.whl (26.6MB)
Collecting six
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting Pillow
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/d6/98/0d360dbc087933679398d73187a503533ec0547ba4ffd2115365605559cc/Pillow-6.1.0-cp35-cp35m-manylinux1_x86_64.whl (2.1MB)
Collecting matplotlib
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/12/d1/7b12cd79c791348cb0c78ce6e7d16bd72992f13c9f1e8e43d2725a6d8adf/matplotlib-3.1.1.tar.gz (37.8MB)
    Complete output from command python setup.py egg_info:
    
    Beginning with Matplotlib 3.1, Python 3.6 or above is required.
    
    This may be due to an out of date pip.
    
    Make sure you have pip >= 9.0.1.
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-02yn83yi/matplotlib/
You are using pip version 8.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
The command '/bin/sh -c pip3 install --no-cache-dir --upgrade setuptools wheel -i https://pypi.tuna.tsinghua.edu.cn/simple &&     pip3 install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple     numpy     protobuf     lmdb     opencv-python     six     Pillow     matplotlib     scikit-image     pyyaml     cython' returned a non-zero code: 1
root@hp-desktop:/data/Dragon/Docker/ubuntu-16.04-cuda9.0-cudnn7# pip -V
pip 19.2.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)
root@hp-desktop:/data/Dragon/Docker/ubuntu-16.04-cuda9.0-cudnn7#

**Comment by PhyscalX** [comment]
Please read the logging message carefully, and google it.
We are not able to test all machines on the earth.

Back to the problem self, Ubuntu 16.04 had released with Python3.5
and  newest Matplotlib requiring 3.6 or higher. Install Matplotlib with a version < 3.1 will be ok.

Close this issue.
